version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      wasmtime:
        patterns:
          - "wasmtime*"
          - "wit-bindgen*"
          - "wasmtime-wasi*"
      patch-updates:
        update-types:
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
