//! WIT bindings for the venue platform, generated by
//! `wasmtime::component::bindgen!`.
//!
//! The shared `nexum:host` interfaces are reused from the runtime's
//! `event-module` bindings via `with`, so the `chain`/`messaging` `Host`
//! impls and the `fault` type an adapter sees are the very ones the core
//! host constructs. The `videre:types` and `videre:value-flow` types
//! generate in the adapter bindgen and the client bindgen remaps onto
//! them, so one Rust type serves the registry and the adapter face alike.
//! `PartialEq` is derived so the registry can compare a polled status
//! against the last delivered one.

/// The provider face: the `videre:venue/venue-adapter` world. An adapter
/// imports only the scoped transport it needs (chain and messaging;
/// outbound HTTP is wasi:http, linked and allowlisted separately) and
/// exports the `videre:venue/adapter` face plus `init`.
mod venue_adapter {
    wasmtime::component::bindgen!({
        path: [
            "../../wit/videre-value-flow",
            "../../wit/videre-types",
            "../../wit/nexum-host",
            "../../wit/videre-venue",
        ],
        world: "videre:venue/venue-adapter",
        imports: { default: async },
        exports: { default: async },
        with: {
            "nexum:host/types": nexum_runtime::bindings::nexum::host::types,
            "nexum:host/chain": nexum_runtime::bindings::nexum::host::chain,
            "nexum:host/messaging": nexum_runtime::bindings::nexum::host::messaging,
        },
        additional_derives: [PartialEq],
    });
}

pub use venue_adapter::VenueAdapter;

/// The keeper-facing `videre:venue/client` import bound host-side. The
/// world imports the interface a module calls; the videre types it uses
/// are reused from the adapter bindings above via `with`, so the
/// `SubmitOutcome` and `VenueError` the registry hands back to a module
/// are the very ones an adapter's `submit` produced. Async, because the
/// `Host` impl awaits the per-adapter mutex and the adapter's own async
/// guest calls.
mod client_host {
    wasmtime::component::bindgen!({
        inline: "
            package videre:client-host;
            world client-host {
                import videre:venue/client@0.1.0;
            }
        ",
        path: [
            "../../wit/videre-value-flow",
            "../../wit/videre-types",
            "../../wit/nexum-host",
            "../../wit/videre-venue",
        ],
        imports: { default: async },
        with: {
            "videre:value-flow/types": super::venue_adapter::videre::value_flow::types,
            "videre:types/types": super::venue_adapter::videre::types::types,
        },
    });
}

/// The host-bound client interface: the `Host` trait the registry implements
/// and the `add_to_linker` the videre extension's linker hook calls.
pub use client_host::videre::venue::client;
/// The shared intent ontology, re-exported at the plain spellings the
/// registry and the `client::Host` impl name.
pub use venue_adapter::videre::types::types::{
    AuthScheme, IntentHeader, IntentStatus, Quotation, RateLimit, Settlement, SubmitOutcome,
    UnsignedTx, VenueError,
};
/// The value-flow vocabulary the header is expressed in.
pub use venue_adapter::videre::value_flow::types as value_flow;

/// Operator-log rendering of the wire `venue-error`: the bindgen
/// `Display` is the `{0:?}` debug form, so logs render through this
/// instead and the rate-limit `retry-after-ms` hint survives.
pub(crate) fn venue_error_message(err: &VenueError) -> std::borrow::Cow<'_, str> {
    use std::borrow::Cow;
    match err {
        VenueError::UnknownVenue => Cow::Borrowed("unknown venue"),
        VenueError::InvalidBody(detail) => Cow::Owned(format!("invalid body: {detail}")),
        VenueError::Unsupported => Cow::Borrowed("unsupported"),
        VenueError::Denied(detail) => Cow::Owned(format!("denied: {detail}")),
        VenueError::RateLimited(rate_limit) => match rate_limit.retry_after_ms {
            Some(ms) => Cow::Owned(format!("rate limited, retry after {ms} ms")),
            None => Cow::Borrowed("rate limited"),
        },
        VenueError::Unavailable(detail) => Cow::Owned(format!("unavailable: {detail}")),
        VenueError::Timeout => Cow::Borrowed("timeout"),
    }
}

#[cfg(test)]
mod display_smoke {
    use super::{RateLimit, VenueError, venue_error_message};

    #[test]
    fn venue_error_message_keeps_the_rate_limit_hint() {
        let hinted = VenueError::RateLimited(RateLimit {
            retry_after_ms: Some(250),
        });
        assert_eq!(
            venue_error_message(&hinted),
            "rate limited, retry after 250 ms"
        );
        let unhinted = VenueError::RateLimited(RateLimit {
            retry_after_ms: None,
        });
        assert_eq!(venue_error_message(&unhinted), "rate limited");
    }
}

/// Bindgen smoke for the `videre:value-flow` types package, compiled under
/// test through a throwaway world that imports the interface. Its value is
/// the identifier-hygiene gate: the test names every generated type,
/// variant, and field by its plain Rust spelling, so a WIT id that collided
/// with a Rust keyword would surface as an `r#` escape and fail to compile
/// here rather than in a downstream binding.
#[cfg(test)]
mod value_flow_smoke {
    wasmtime::component::bindgen!({
        inline: "
            package videre:value-flow-smoke;
            world smoke {
                import videre:value-flow/types@0.1.0;
            }
        ",
        path: ["../../wit/videre-value-flow"],
    });

    #[test]
    fn identifiers_bind_unescaped() {
        use videre::value_flow::types::{Asset, AssetAmount, Erc20};

        let erc20 = Erc20 {
            token: vec![0u8; 20],
        };
        let _ = Asset::Native;
        let asset = Asset::Erc20(erc20);

        let amount = AssetAmount {
            asset,
            amount: Vec::new(),
        };
        assert!(amount.amount.is_empty());
    }
}

/// Bindgen smoke for the `videre:types` and `videre:venue` packages,
/// mirroring the value-flow smoke above: a throwaway world imports the
/// client interface and, transitively, the types interface and its
/// value-flow dependency. The test names every generated type, case, and
/// field by its plain Rust spelling, and a dummy `client` host impl pins
/// the five function signatures, so a keyword collision or an accidental
/// signature change fails this build rather than a downstream binding.
#[cfg(test)]
mod client_smoke {
    wasmtime::component::bindgen!({
        inline: "
            package videre:client-smoke;
            world smoke {
                import videre:venue/client@0.1.0;
            }
        ",
        path: [
            "../../wit/videre-value-flow",
            "../../wit/videre-types",
            "../../wit/nexum-host",
            "../../wit/videre-venue",
        ],
    });

    use videre::types::types::{
        AuthScheme, IntentHeader, IntentStatus, Quotation, RateLimit, Settlement, SubmitOutcome,
        UnsignedTx, VenueError,
    };
    use videre::value_flow::types::{Asset, AssetAmount};

    struct DummyClient;

    impl videre::venue::client::Host for DummyClient {
        fn quote(&mut self, _venue: String, _body: Vec<u8>) -> Result<Quotation, VenueError> {
            Err(VenueError::UnknownVenue)
        }

        fn submit(&mut self, _venue: String, _body: Vec<u8>) -> Result<SubmitOutcome, VenueError> {
            Err(VenueError::UnknownVenue)
        }

        fn observe(&mut self, _venue: String, _receipt: Vec<u8>) -> Result<(), VenueError> {
            Err(VenueError::UnknownVenue)
        }

        fn status(
            &mut self,
            _venue: String,
            _receipt: Vec<u8>,
        ) -> Result<IntentStatus, VenueError> {
            Err(VenueError::UnknownVenue)
        }

        fn cancel(&mut self, _venue: String, _receipt: Vec<u8>) -> Result<(), VenueError> {
            Err(VenueError::UnknownVenue)
        }
    }

    fn amount(bytes: Vec<u8>) -> AssetAmount {
        AssetAmount {
            asset: Asset::Native,
            amount: bytes,
        }
    }

    #[test]
    fn identifiers_bind_unescaped() {
        use videre::venue::client::Host;

        let _ = AuthScheme::Eip1271;
        let _ = AuthScheme::Eip712;

        let header = IntentHeader {
            gives: amount(vec![1]),
            wants: amount(Vec::new()),
            settlement: Settlement { chain: 1 },
            authorisation: AuthScheme::Eip712,
        };
        assert!(header.wants.amount.is_empty());

        let _ = IntentStatus::Pending;
        let _ = IntentStatus::Open;
        let _ = IntentStatus::Fulfilled;
        let _ = IntentStatus::Cancelled;
        let _ = IntentStatus::Expired;

        let tx = UnsignedTx {
            chain: 1,
            to: Vec::new(),
            value: Vec::new(),
            data: Vec::new(),
        };
        let _ = SubmitOutcome::Accepted(Vec::new());
        let _ = SubmitOutcome::RequiresSigning(tx);

        let quotation = Quotation {
            gives: amount(vec![1]),
            wants: amount(Vec::new()),
            fee: amount(Vec::new()),
            valid_until_ms: 0,
        };
        assert!(quotation.fee.amount.is_empty());

        let _ = VenueError::UnknownVenue;
        let _ = VenueError::InvalidBody(String::new());
        let _ = VenueError::Unsupported;
        let _ = VenueError::Denied(String::new());
        let _ = VenueError::RateLimited(RateLimit {
            retry_after_ms: Some(250),
        });
        let _ = VenueError::Unavailable(String::new());
        let _ = VenueError::Timeout;

        let mut client = DummyClient;
        assert!(client.quote(String::new(), Vec::new()).is_err());
        assert!(client.submit(String::new(), Vec::new()).is_err());
        assert!(client.observe(String::new(), Vec::new()).is_err());
        assert!(client.status(String::new(), Vec::new()).is_err());
        assert!(client.cancel(String::new(), Vec::new()).is_err());
    }
}
